baseurl = "https://divadnojnarg.github.io"
relativeurls = true
languageCode = "en-us"
tags = ["Zurich", "renal physiology", "mathematical physiology", "calcium", "phosphate", "ShinyApps", "R"]

title = "Hi, I am David"
theme = "osprey"
googleAnalytics = ""
disqusShortname = "divadnojnarg"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir ="/Users/macdavidgranjon/Documents/Websites/divadnojnarg.github.io"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    tagline = "Hi, I am David"
    author = "David Granjon"
    description = "PhD in Mathematical Physiology, Renal Physiology, Zurich."
    logoBig = "/images/fractal-logo.png"
    logoSmall = "/images/fractal-logo.png"
    
    linkedin = "david-granjon-88625968"
    github = "divadnojnarg"
    twitter = "divadnojnarg"
    
    email = "dgranjon@ymail.com"
    
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credits = true
    
    # Cache busting of static resources (additional set up required)
    cacheBustCSS = false
    cacheBustJS = false
    
    # Choose either Formspree contact form or Basin contact form
    ajaxFormspree = true
    ajaxFormspreeGold = false
    ajaxBasin = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


[[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 2
    
[[menu.main]]
    name = "About"
    url = "/cv.pdf"
    weight = 3
    
[[menu.main]]
    name = "RinteRface"
    url = "https://rinterface.com"
    weight = 4