baseurl = "https://divadnojnarg.github.io"
relativeurls = true
languageCode = "en-us"
tags = ["Zurich", "renal physiology", "mathematical physiology", "calcium", "phosphate", "ShinyApps", "R"]

title = "Hi, I am David"
theme = "osprey"
googleAnalytics = ""
disqusShortname = "divadnojnarg"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir ="/Users/macdavidgranjon/Documents/divadnojnarg.github.io"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 2
    
[[menu.main]]
    name = "About"
    url = "/cv.pdf"
    weight = 3
    
[[menu.main]]
    name = "Shiny.Server"
    url = "http://130.60.24.205"
    weight = 4

[params]
    author = "David Granjon"
    description = "PhD in Mathematical Physiology, Renal Physiology, Zurich."
    logoBig = "/images/fractal-logo.png"
    logoSmall = "/images/fractal-logo.png"
    
    linkedin = "david-granjon-88625968"
    github = "divadnojnarg"
    twitter = "divadnojnarg"
    
    email = "dgranjon@ymail.com"
    
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credits = true

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

