baseurl = "https://divadnojnarg.github.io"
relativeurls = true
languageCode = "en-us"
title = "Hi, I am David"
theme = "osprey"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir ="/Users/macdavidgranjon/Documents/divadnojnarg.github.io"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Work"
    url = "/#work"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 2
[[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 3
    
[[menu.main]]
    name = "About"
    url = "/cv.pdf"
    weight = 4

[params]
    author = "David Granjon"
    description = "PhD in Mathematical Physiology, Renal Physiology, Zurich."
    logoBig = "/images/fractal-logo.png"
    logoSmall = "/images/fractal-logo.png"
    
    linkedin = "david-granjon-88625968"
    github = "divadnojnarg"
    
    email = ""
    
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credits = true

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

